with CTE AS (
SELECT
TO_TIMESTAMP(TIME) AS TIME_DATE,
DATE(TO_TIMESTAMP(TIME)) AS DATE,
HOUR(TO_TIMESTAMP(TIME)) AS HOUR,

CASE WHEN DAYNAME(TO_TIMESTAMP(TIME)) IN ('SAT','SUN')
THEN 'WEEKEND'
ELSE 'WEEKDAY'
END AS DAY_TYPE,


{{station('TIME')}} AS STATION_OF_YEAR



FROM {{source('demo','weather')}}
)

select * from CTE