with CTE AS (
SELECT
TO_TIMESTAMP(TIME) AS TIME_DATE,
DATE(TO_TIMESTAMP(TIME)) AS DATE,
HOUR(TO_TIMESTAMP(TIME)) AS HOUR,

CASE WHEN DAYNAME(TO_TIMESTAMP(TIME)) IN ('SAT','SUN')
THEN 'WEEKEND'
ELSE 'WEEKDAY'
END AS DAY_TYPE,

CASE WHEN MONTH(TO_TIMESTAMP(TIME)) IN (12,1,2)
THEN 'WINTER'
WHEN MONTH(TO_TIMESTAMP(TIME)) IN (3,4,5)
THEN 'SPRING'
WHEN MONTH(TO_TIMESTAMP(TIME)) IN (6,7,8)
THEN 'SUMMER'
ELSE 'AUTUMN'
END AS STATION_OF_YEAR


FROM {{source('demo','weather')}}
)

select * from CTE